language: java
jdk:
  - oraclejdk8
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e 'CREATE DATABASE db_sbx;'
  - mysql -u root db_sbx < doc/script/mysql/schema.sql
  - mysql -u root db_sbx < doc/script/mysql/init-data.sql
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p123456
  - sudo service mysql restart
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B

