#springboot配置文件
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_sbx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

# mybatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mst.sbx
  mapper-locations: classpath:mapper/**/*.xml
